title: "Curso Javascript Fullstack"
remote_theme: pmarsceill/just-the-docs
logo: "https://res.cloudinary.com/boolean-spa/image/upload/v1620172881/logo-horizontal_hqou69.png"
aux_links:
  "Academia":
    - "https://boolean.cl"
  "Empresas":
    - "https://boolean.cl/servicios"

aux_links_new_tab: true
